### ISSUE TITLE
Build broken on Linux

### ISSUE THREAD

**Issue by schmatzler** [RigsOfRods/rigs-of-rods#438]
I've tried to build the current HEAD c692412efa67780afe8bacebfea6700dd945b91e on Slackware64 here (gcc 4.9.3).

It fails at 24% with this error:

```
/tmp/txz/rigsofrods-20150922/source/main/gfx/SkyManager.cpp: In member function 'void SkyManager::loadScript(Ogre::String, int, int)':
/tmp/txz/rigsofrods-20150922/source/main/gfx/SkyManager.cpp:97:40: error: 'class Caelum::CaelumPlugin' has no member named 'loadCaelumSystemFromScript'
   Caelum::CaelumPlugin::getSingleton().loadCaelumSystemFromScript (mCaelumSystem, script);
                                        ^
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/__/gfx/SkyManager.cpp.o] Error 1
```

**Comment by Hiradur** [comment]
Are you using https://github.com/RigsOfRods/caelum ?

**Comment by schmatzler** [comment]
Whoops, I overlooked that you updated this, too. Now it builds.

Slackware can get new packages now :)

**Comment by Mailaender** [comment]
Are there plans to make this work with regular versions of Caelum?

**Comment by Hiradur** [comment]
> Are there plans to make this work with regular versions of Caelum?

define "regular versions of Caelum", please.

**Comment by Mailaender** [comment]
Current version 0.6.1 available via e.g. https://software.opensuse.org/package/caelum

**Comment by Hiradur** [comment]
0.6.1 is very old and development died after that release. Now various forks exist with minor fixes of bugs and builds.

The 0.6.1 release probably doesn't work with Ogre 1.9.

**Comment by Mailaender** [comment]
A united upstream instead of multiple per-project forks would make packaging easier.

**Comment by Hiradur** [comment]
An attempt to do this was done here: https://bitbucket.org/ogreaddons/

Our Caelum repository is a fork of that one because it didn't build and there was no activity for months. But I see it's been fixed now: https://bitbucket.org/ogreaddons/caelum/commits/8620df4b7c43fb1ced39487ff551d42d65c32da8

**Comment by Mailaender** [comment]
A tagged release that is known to work and build would help as well.

**Comment by Hiradur** [comment]
https://github.com/RigsOfRods/caelum works and I could tag a release, but which version should I choose?

**Comment by Mailaender** [comment]
0.6.2 is mentioned on https://github.com/RigsOfRods/rigs-of-rods/blob/master/BUILDING.md#dependencies

**Comment by Hiradur** [comment]
Right, I copied it from our wiki and I can't remember why it's named so, probably to make clear that 0.6.1 won't work.

**Comment by Hiradur** [comment]
Before making a release the latest patches from https://code.google.com/p/caelum/source/list
should be applied (they are missing, I checked some).

Paged Geometry would need a release as well.

**Comment by Mailaender** [comment]
I imported https://github.com/Mailaender/caelum preserving the commit history and the bug tracker entries from Google Code. Can transfer ownership.

**Comment by Hiradur** [comment]
@Mailaender Let me look into it later. I think our Caelum repo is imported from https://bitbucket.org/ogreaddons/ but I didn't create it and I don't know why it was chosen over the official repo on Google code.
Maybe I just replace our repo with a new import.

**Comment by Hiradur** [comment]
@Mailaender I imported the caelum repo so we don't have to deal with user permissions: https://github.com/RigsOfRods/ogre-caelum

However, as it turned out, it doesn't compile with Ogre 1.9 and now I'm not really sure what I should do. Fix it and ditch the other one or keep the old one, apply the missing patches and forget about it. I'm leaning towards the latter, what do you think?

**Comment by Mailaender** [comment]
I don't know. If Ogre Addons is the proper upstream than you probably should join the team. I asked for the same thing there: https://bitbucket.org/ogreaddons/caelum/issues/1/tagged-releases Let's see if anyone responds.

**Comment by Hiradur** [comment]
@Mailaender I decided to patch https://github.com/Mailaender/caelum for Ogre 1.9 and use this for a release.
Reason: It's from the official source and guaranteed to not be a downgrade from older versions. It contains samples and documentation, something which the repo at ogreaddons is lacking. The ogreaddons repo is also lacking license information, contributors etc.

That being said, if the ogreaddons team would like to use our repo instead of theirs they should go ahead so we could then centralize all efforts.

I'm going to prepare the repo and tag the release later today.

**Comment by Hiradur** [comment]
@Mailaender Here it goes: https://github.com/RigsOfRods/ogre-caelum
This version is compatible with Ogre 1.9 and 1.8, maybe older and newer versions, too

**Comment by Mailaender** [comment]
Updated https://build.opensuse.org/request/show/353127.

**Comment by Hiradur** [comment]
@Mailaender :+1:

**Comment by Mailaender** [comment]
This also finally fixes RoR. https://build.opensuse.org/request/show/353149

**Comment by Hiradur** [comment]
@Mailaender Awesome!
