### ISSUE TITLE
Arch Linux build issue

### ISSUE THREAD

**Issue by gdm413229** [RigsOfRods/rigs-of-rods#1420]
# My issue with building Rigs of Rods

## Tick-box summary of what goes through the linker/librarian without trouble

 - [x] AngelScript Addons
 - [x] RoR Configurator
 - [x] RoR Version Information
 - [x] SocketW
 - [ ] Rigs of Rods Executable

## Description of the build issue

Everything compiled and assembled just fine, but the proper Rigs of Rods executable didn't get built due to an error related to undefined references that came out of the linker.  Rigs of Rods requires SocketW to build and run, and if you can make the source in a way that SocketW is optional or not required for network play, that will be appreciated.  Linker error messages can be found below the description of this issue.

Other Arch Linux users can post their fixes for linking against SocketW, just so I don't have to use WINE, Windows, Ubuntu or Macintosh machines for RoR.

### Linker error messages

```
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libSocketW.so: undefined reference to `X509_set_notBefore'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libSocketW.so: undefined reference to `X509_set_notAfter'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libSocketW.so: undefined reference to `SSLv23_method'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libSocketW.so: undefined reference to `SSL_load_error_strings'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/../../../../lib/libSocketW.so: undefined reference to `SSL_library_init'
```

# Machine Specifications
## Hardware Specifications
Component | Name
----------|---------
CPU | AMD FX-8350
Graphics Adapter | NVIDIA GeForce GTX 1070
RAM | 16GB DDR3
Motherboard | ASUS 970 PRO GAMING/AURA
Internal Storage | ST2000DX001-1NS164 [reported by SATA host adapter]
## Software Specifications
Software | Version or Name
------------|----------
GNU GCC | 7.2.1
Linux Kernel | 4.14
Linux Kernel Architecture | x86-64
Linux Distribution | Arch Linux

**Comment by tritonas00** [comment]
this is because socketw cant build with openssl 1.1

see first comment here https://aur.archlinux.org/packages/socketw/ and https://github.com/RigsOfRods/rigs-of-rods/issues/1385

**Comment by gdm413229** [comment]
Built SocketW using osvein's fixed PKGBUILD, found from this [gist](https://gist.github.com/osvein/744a4edd25d97ed1cdb3c5f219c3acee).  The new PKGBUILD builds SocketW against OpenSSL 1.0, and my issue is related to linking RoR against the SocketW build courtesy of this new PKGBUILD.

**Comment by tritonas00** [comment]
try add those linker flags to ror also

**Comment by gdm413229** [comment]
Makes me think of updating the rigsofrods-git PKGBUILD, and you can tell me where to place those LDFLAGS in the command line or PKGBUILD.

**Comment by tritonas00** [comment]
in the build function, before the cmake add:

`export LDFLAGS='-L/usr/lib/openssl-1.0/ -lssl -lcrypto'`

**Comment by gdm413229** [comment]
Tried your suggestion, but CMake is erroring, with the output below.

```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.3", minimum required is "3.0") 
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/lib/ccache/bin/cc
-- Check for working C compiler: /usr/lib/ccache/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.31
-- Checking for module 'gdk-pixbuf-2.0'
--   Found gdk-pixbuf-2.0, version 2.36.10
-- Found Git: /usr/bin/git (found version "2.15.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for OGRE...
-- OGRE_PREFIX_WATCH changed.
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /opt/OGRE-1.9/lib/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /opt/OGRE-1.9/lib/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /opt/OGRE-1.9/lib/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /opt/OGRE-1.9/lib/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /opt/OGRE-1.9/lib/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /opt/OGRE-1.9/lib/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /opt/OGRE-1.9/lib/libOgreOverlay.so
-- Looking for OIS...
-- OIS_PREFIX_PATH changed.
-- Checking for module 'OIS'
--   Found OIS, version 1.3.0
-- Found OIS: /usr/lib/libOIS.so
-- Found MyGUI: /opt/MyGUI-OGRE1.9/include/MYGUI  
-- Found OpenAL: /usr/lib/libopenal.so  
-- Found SocketW: /usr/include  
-- Found AngelScript: /usr/include  
-- Found CURL: /usr/lib/libcurl.so (found version "7.57.0") 
-- Found Caelum: /opt/Caelum-OGRE1.9/include/Caelum  
-- Found PagedGeometry: /opt/PagedGeometry-OGRE1.9/include/PagedGeometry  
CMake Error: Could not open file for write in copy operation /CMakeFiles/plugins.cfg.tmp
CMake Error: : System Error: No such file or directory
CMake Error at source/main/CMakeLists.txt:602 (configure_file):
  configure_file Problem configuring file


-- Found wxWidgets: -pthread;;;-lwx_baseu-3.0;-lwx_gtk2u_core-3.0;-lwx_gtk2u_html-3.0;-lwx_baseu_net-3.0;-lwx_gtk2u_adv-3.0 (found version "3.0.3") 
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: /opt/OGRE-1.9/lib/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: /opt/OGRE-1.9/lib/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: /opt/OGRE-1.9/lib/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: /opt/OGRE-1.9/lib/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: /opt/OGRE-1.9/lib/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: /opt/OGRE-1.9/lib/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: /opt/OGRE-1.9/lib/libOgreOverlay.so
-- Looking for OIS...
-- Found OIS: /usr/lib/libOIS.so
-- The following OPTIONAL packages have been found:

 * Git
 * SocketW
 * CURL
 * Caelum
 * PagedGeometry
 * AngelScript
 * PkgConfig
 * OpenAL

-- The following REQUIRED packages have been found:

 * PythonInterp (required version >= 3.0)
 * wxWidgets
 * Threads
 * OGRE
 * OIS
 * MyGUI

-- Configuring incomplete, errors occurred!
See also "/home/rae/rigsofrods-git/src/rigs-of-rods/build/CMakeFiles/CMakeOutput.log".
See also "/home/rae/rigsofrods-git/src/rigs-of-rods/build/CMakeFiles/CMakeError.log".
```

**Comment by tritonas00** [comment]
latest master is broken see https://github.com/RigsOfRods/rigs-of-rods/pull/1421#issuecomment-350824710 :p

**Comment by gdm413229** [comment]
If you have thought of any solutions, inform me.

**Comment by tritonas00** [comment]
the 'plugins.cfg' problem is fixed now, can you re-try?

**Comment by gdm413229** [comment]
plugins.cfg is provided by cloning the PKGBUILD via the Arch User Repository.  Don't delete the AUR version of plugins.cfg when packaging the Git version of Rigs of Rods for Arch.

**Comment by tritonas00** [comment]
Just compiled RoR latest git successfully on fully updated Arch, check the first comment here https://aur.archlinux.org/packages/rigsofrods-git/

> export LDFLAGS='-L/usr/lib/openssl-1.0/ -lssl -lcrypto'

fixes the linker errors, as i suspected

**Comment by tritonas00** [comment]
this can be closed

**Comment by only-a-ptr** [comment]
☺️
