### ISSUE TITLE
Building on archlinux -  OgreOverlayElement.h: No such file or directory

### ISSUE THREAD

**Issue by masterkorp** [RigsOfRods/rigs-of-rods#145]
```
cmake .
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   regex
-- checking for module 'gtk+-2.0'
--   found gtk+-2.0, version 2.24.27
-- checking for module 'gdk-pixbuf-2.0'
--   found gdk-pixbuf-2.0, version 2.31.3
-- checking for module 'OGRE'
--   found OGRE, version 1.9.0
-- checking for module 'OGRE-Terrain'
--   found OGRE-Terrain, version 1.9.0
-- checking for module 'OGRE-Paging'
--   found OGRE-Paging, version 1.9.0
-- checking for module 'OGRE-RTShaderSystem'
--   found OGRE-RTShaderSystem, version 1.9.0
-- checking for module 'OIS'
--   found OIS, version 1.3.0
-- Found CURL: /usr/lib64/libcurl.so (found version "7.41.0") 
-- Found OpenAL: /usr/lib64/libopenal.so  
-- checking for module 'MYGUI'
--   found MYGUI, version 3.2.2
-- MYGUI Enabled:      	YES
-- MYGUI_INCLUDE_DIRS: 	/usr/include/MYGUI
-- MYGUI_LIBRARY_DIRS: 	
-- MYGUI_LIBRARIES:    	MyGUIEngine;/usr/lib64/libMyGUI.OgrePlatform.so
-- OPENAL Enabled:      	YES
-- OPENAL_INCLUDE_DIRS: 	/usr/include/AL
-- OPENAL_LIBRARY_DIRS: 	
-- OPENAL_LIBRARIES:    	/usr/lib64/libopenal.so
-- CURL Enabled:      	YES
-- CURL_INCLUDE_DIRS: 	/usr/include
-- CURL_LIBRARY_DIRS: 	
-- CURL_LIBRARIES:    	/usr/lib64/libcurl.so
-- SOCKETW Enabled:      	YES
-- SOCKETW_INCLUDE_DIRS: 	/usr/include
-- SOCKETW_LIBRARY_DIRS: 	
-- SOCKETW_LIBRARIES:    	/usr/lib64/libSocketW.so
-- PAGED Enabled:      	NO
-- CAELUM Enabled:      	NO
-- ANGELSCRIPT Enabled:      	NO
-- Found wxWidgets: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/masterkorp/Documents/projects/forks/rigs-of-rods
```

```
make
Scanning dependencies of target RoR
[  0%] Building CXX object source/main/main_sim/CMakeFiles/RoR.dir/__/audio/Sound.cpp.o
[  0%] Building CXX object source/main/main_sim/CMakeFiles/RoR.dir/__/audio/SoundManager.cpp.o
[  1%] Building CXX object source/main/main_sim/CMakeFiles/RoR.dir/__/audio/SoundScriptManager.cpp.o
In file included from /home/masterkorp/Documents/projects/forks/rigs-of-rods/source/main/audio/SoundScriptManager.cpp:24:0:
/home/masterkorp/Documents/projects/forks/rigs-of-rods/source/main/physics/Beam.h:32:32: fatal error: OgreOverlayElement.h: No such file or directory
 #include <OgreOverlayElement.h>
                                ^
compilation terminated.
source/main/main_sim/CMakeFiles/RoR.dir/build.make:100: recipe for target 'source/main/main_sim/CMakeFiles/RoR.dir/__/audio/SoundScriptManager.cpp.o' failed
make[2]: *** [source/main/main_sim/CMakeFiles/RoR.dir/__/audio/SoundScriptManager.cpp.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'source/main/main_sim/CMakeFiles/RoR.dir/all' failed
make[1]: *** [source/main/main_sim/CMakeFiles/RoR.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

Commit b5320d455e9f9cd4fba2caae9cc1f895d5cb5f3b

**Comment by schmatzler** [comment]
Do you have Ogre 1.8 or 1.9 installed? It only works with 1.8 at this time.

**Comment by masterkorp** [comment]
@schmatzler You're right I am on 1.9

````
$ pacman -Qi ogre 
Name           : ogre
Version        : 1.9.0-8
Description    : Scene-oriented, flexible 3D engine written in C++
Architecture   : x86_64
URL            : http://www.ogre3d.org
Licenses       : custom:MIT
Groups         : None
Provides       : None
Depends On     : boost-libs  freeimage  freetype2  libxaw  libxrandr
                 nvidia-cg-toolkit  zziplib  ois  glu  tinyxml
Optional Deps  : cppunit: unit testing
                 intel-tbb: better threading support [installed]
                 poco: portability
                 boost: for developing using ogre [installed]
                 ogre-docs: documentation
Required By    : mygui
Optional For   : cegui
Conflicts With : None
Replaces       : None
Installed Size : 153.28 MiB
Packager       : Evangelos Foutras <evangelos@foutrelis.com>
Build Date     : Tue 04 Nov 2014 10:54:59 PM WET
Install Date   : Fri 05 Dec 2014 11:37:17 PM WET
Install Reason : Installed as a dependency for another package
Install Script : Yes
Validated By   : Signature
```

Should not cmake trow an error ?

**Comment by schmatzler** [comment]
Well, the error is that it cannot be built with 1.8 at this time.
Maybe the devs can shed some light if they want to port all the stuff over to 1.9 soon. In the meantime you have to use 1.8 and the error will go away. ;)

**Comment by Max98** [comment]
I've managed to build RoR with 1.9 back then (http://www.rigsofrods.com/threads/117969-RoR-With-Ogre-1-9-and-latest-AngelScript) but it's pretty unstable and needs a lot of fixing.
We have to fix the game before upgrading and taking care of the libs. :P

**Comment by tritonas00** [comment]
Check my PKGBUILDS https://github.com/tritonas00/rigsofrods-git

I send everything send to /opt/ror so no bother for conflicting versions with those older libs :)

**Comment by Hiradur** [comment]
OGRE will be updated eventually but RoR may just skip to OGRE 2.0 after it's released. 
We could put a check for OGRE version >1.8 into CMake to prevent issues like these.

**Comment by Hubbitus** [comment]
I have same problem on Fedora:
```
In file included from /home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/main/audio/SoundScriptManager.cpp:24:0:
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/main/physics/Beam.h:33:32: fatal error: OgreOverlayElement.h: No such file or directory
 #include <OgreOverlayElement.h>
```
Wiki http://www.rigsofrods.com/wiki/pages/Compiling_Sources_under_Linux now said OGRE 1.9 recommended and I have such:
$ rpm -q ogre
ogre-1.9.0-12.fc23.x86_64

Problem what that file placed /usr/include/OGRE/Overlay/OgreOverlayElement.h
I read BUILDING.md but it seams *_INCLUDE_DIRS vars does not help me. Is there standard way to provide additional include pathes or I should patch RoR?

**Comment by Hiradur** [comment]
@Hubbitus the 0.4.5.1 tagged release needs Ogre 1.8, the upgrade to Ogre 1.9 was done after that release.

**Comment by Hubbitus** [comment]
Is there stable tag for that? Or what branch I should treat as stable and build?

**Comment by Hiradur** [comment]
0.4.6.0 is not released/tagged yet but the master branch can be considered to be more stable than 0.4.5.1.

**Comment by Hubbitus** [comment]
Ok, thanks. For master c10f9acd5ccc6147a507ec2baed8f2e564d94bd0 I have similar error but with another file:
```
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-c10f9acd5ccc6147a507ec2baed8f2e564d94bd0/source/main/network/NetworkStreamManager.h:35:21: fatal error: SocketW.h: No such file or directory
 #include "SocketW.h"
```

We have such file in SocketW subdirectory: /usr/include/SocketW/SocketW.h

What options I should use to customize include directories? Should I fill separate issue?

**Comment by Hiradur** [comment]
```
SOCKETW_INCLUDE_DIRS
```

Should be it, I realized it's missing from building.md. 
If it doesn't work you can create a new ticket

**Comment by Hubbitus** [comment]
Thank you.
